{% set name = "tango-starter" %}
{% set version = "8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/starter/-/releases/Starter-{{ version }}/downloads/starter-with-submodules-Starter-{{ version }}.tar.gz
  sha256: 4ff742da1ad8535cd14f013b58201e9753293e50a3f78f6649edd2606be0e6e5
  patches:   # [win]
    - find-zmq-435.patch   # [win]

build:
  number: 1

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config              # [unix]
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    # Starter --help returns 255
    - Starter --help 2>&1 | grep usage         # [unix]
    - Starter.exe --help 2>&1 | findstr usage  # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Device server to control Tango components
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This device server is able to control Tango components (database, device servers, clients...).
    It is able to start or stop and to report the status of these components.
  dev_url: https://gitlab.com/tango-controls/starter

extra:
  recipe-maintainers:
    - beenje
