{% set name = "tango-starter" %}
{% set version = "8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/starter/-/archive/Starter-{{ version }}/starter-Starter-{{ version }}.tar.gz
  sha256: af51cc76ffd85c3023117f9d4bf720ea53174900f00f92a8ae02c70713566aee
  patches:
    - cmake-macos.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb
    - omniorb-libs

test:
  commands:
    # Starter --help returns 255
    - Starter --help 2>&1 | grep usage

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Device server to control Tango components
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This device server is able to control Tango components (database, device servers, clients...).
    It is able to start or stop and to report the status of these components.
  dev_url: https://gitlab.com/tango-controls/starter

extra:
  recipe-maintainers:
    - beenje
