schema_version: 1

context:
  version: "9.0"

recipe:
  name: tango-starter-split
  version: ${{ version }}

source:
  url: https://gitlab.com/tango-controls/starter/-/releases/Starter-${{ version }}/downloads/starter-with-submodules-Starter-${{ version }}.tar.gz
  sha256: 8c747abcacc53c6431d9c7a0c01f49f2810a7535685692846bc6055063c51c5f
  patches:
    - if: win
      then: find-zmq-435.patch

build:
  number: 2

outputs:
  - staging:
      name: tango-starter-build
    requirements:
      build:
        - cmake
        - ninja
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - if: unix
          then:
            - pkg-config
      host:
        - cppzmq
        - cpptango
        - omniorb-libs
    build:
      script:
        file: build

  - package:
      name: tango-starter
    inherit: tango-starter-build
    build:
      files:
        - if: unix
          then:
            - bin/Starter
          else:
            - Library/bin/Starter.exe
    tests:
      - script:
          - if: unix
            then:
              # Starter --help returns 255, so grep the stderr for test
              - Starter --help 2>&1 | grep -i usage
            else:
              - Starter.exe --help 2>&1 | findstr /i usage

  - package:
      name: tango-starter-dbg
    inherit:
      from: tango-starter-build
      run_exports: false
    build:
      skip:
        - not linux
      dynamic_linking:
        # Prevent dbg file to be modified
        # Will raise CRC mismatch otherwise!
        binary_relocation: false
      files:
        - lib/debug/Starter.dbg
    requirements:
      run:
        - ${{ pin_subpackage('tango-starter', exact=True) }}
    tests:
      - package_contents:
          files:
            - lib/debug/Starter.dbg

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Device server to control Tango components
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This device server is able to control Tango components (database, device servers, clients...).
    It is able to start or stop and to report the status of these components.
  homepage: https://www.tango-controls.org
  repository: https://gitlab.com/tango-controls/starter

extra:
  feedstock-name: tango-starter
  recipe-maintainers:
    - beenje
